version: 2.1

orbs:
  go: circleci/go@1.7.1

jobs:
  test:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - run:
          name: Setup Go Environment
          command: |
            go mod download
            go mod tidy
      - go/load-cache
      - go/save-cache
      - run:
          name: Run tests
          command: go test -v ./...
      - store_test_results:
          path: test-results

workflows:
  version: 2
  test:
    jobs:
      - test 